SELECT DISTINCT 
                         SPA_KOPF.SPANR AS Rückmeldenummer,
						 ARTIKEL.SARTIKELNR AS Werkzeugnummer,
						 SPA_KOPF.SZUSINFO20 as Auftragsnummer,
						 ARTIKEL.SZEICHNR as Zeichnungsnummer,
						 FA_STAMM.SFABEZ as KUNDE,
						 MANDANT.SMANDBEZ as MANDANT,
						 MM_KOPF.SMMNR AS 'MM-BEZ',
						 MM_REV.DSOLL AS SOLLMAß, 
						 MM_REV.NEINHEIT,
						 ARTIKEL.SZEICHBEZ
FROM            MM_REV INNER JOIN
                         PP_PAB_PP_REV ON MM_REV.NLFDMMNR = PP_PAB_PP_REV.NLFDMMNR 
						 INNER JOIN
                         SPA_KOPF 
						 INNER JOIN ARTIKEL ON SPA_KOPF.NLFDARTIKELNR = ARTIKEL.NLFDARTIKELNR 
							INNER JOIN PP_REV ON SPA_KOPF.NLFDPPLNR = PP_REV.NLFDPPLNR 
							INNER JOIN PP_PAB_REF ON PP_REV.NLFDPPLNR = PP_PAB_REF.NLFDPPLNR 
						 ON PP_PAB_PP_REV.NLFDPABNR = PP_PAB_REF.NLFDPABNR 
						 INNER JOIN MANDANT ON SPA_KOPF.NLFDMANDNR=MANDANT.NLFDMANDNR 
						 INNER JOIN FA_STAMM ON SPA_KOPF.NLFDFANR=FA_STAMM.NLFDFANR 
						 INNER JOIN MM_KOPF ON MM_REV.NLFDMMNR=MM_KOPF.NLFDMMNR

						 WHERE        (SPA_KOPF.SPANR = 'I0066844') AND (PP_REV.NREVFLAG = '1')
use wefa


select * from CKMM_MITTELSTAND WHERE SDTSERIAL = '1523' AND SPTSERIAL='1524'
UPDATE CKMM_MITTELSTAND 
SET SDTSERIAL = '984' , SPTSERIAL = '985'
where SPANR = 'TEST 123'

select * from MM_MITTELSTAND_CK;

INSERT INTO MM_MITTELSTAND_CK ( SPANR, SZUSINFO20, SDTSERIAL, SPTSERIAL, SFABEZ, SPRUEFER, SZEICHBEZ, SARTIKELNR, SMANDBEZ, DM101, DM102, DM103, DM104, DM105, DM106, DM9RMIN, DM9RMAX, DM9RAUSSEN, DSM101, DSM102, DSM103, DSM104, DSM105, DSM106, DSM9RMIN, DSM9RMAX, DSM9RAUSSEN, DMMANZAHL)
VALUES ('TEST 123', '1231231', '1523', '1524', 'CK', 'NVE', 'Bohrmaschine', 'I1008','PC1' ,'0.3001', '0.3002', '0.3003', '0.3004', '0.3005', '0.3006', '0.30067', '0.30068', '0.30069', '0.3000','0.3000', '0.3001','0.4001','0.5001','0.6001', '0.7001', '0.8000','0.9000', '9')

INSERT INTO MM_MITTELSTAND_CK ( SPANR, SZUSINFO20, SDTSERIAL, SPTSERIAL, SFABEZ, SPRUEFER, SZEICHBEZ, SARTIKELNR, SMANDBEZ, DM101, DM102, DM103, DM104, DM105, DM106, DM9RMIN, DM9RMAX, DM9RAUSSEN, DSM101, DSM102, DSM103, DSM104, DSM105, DSM106, DSM9RMIN, DSM9RMAX, DSM9RAUSSEN, DMMANZAHL)
VALUES ('TEST 123', '1231231', '1234', '1237', 'CK', 'NVE', 'Bohrmaschine', 'I1008','PC1' ,'0.3001', '0.3002', '0.3003', '0.3004', '0.3005', '0.3006', '0.30067', '0.30068', '0.30069', '0.3000','0.3000', '0.3001','0.4001','0.5001','0.6001', '0.7001', '0.8000','0.9000', '9')



Select DISTINCT SPANR, SZUSINFO20, SDTSERIAL, SPTSERIAL, SFABEZ, SPRUEFER, SZEICHBEZ, SARTIKELNR, DM101, DM102, DM103, DM104, DM105, DM106, DM9RMIN, DM9RMAX, DM9RAUSSEN, DSM101, DSM102, DSM103, DSM104, DSM105, DSM106, DSM9RMIN, DSM9RMAX, DSM9RAUSSEN, DMMANZAHL
from MM_MITTELSTAND_CK Where SPANR = 'TEST 123'

Select SPANR, SZUSINFO20, SDTSERIAL, SPTSERIAL, SFABEZ, SPRUEFER, SZEICHBEZ, SARTIKELNR, DM101, DM102, DM103, DM104, DM105, DM106, DM9RMIN, DM9RMAX, DM9RAUSSEN, DSM101, DSM102, DSM103, DSM104, DSM105, DSM106, DSM9RMIN, DSM9RMAX, DSM9RAUSSEN, DMMANZAHL
from MM_MITTELSTAND_CK Where SPANR = 'TEST 123'

-- Drop table
DROP TABLE MM_MITTELSTAND_CK

-- Prerequisites for Application
-- Prerequisites for Application
CREATE TABLE MM_MITTELSTAND_CK ( SPANR nvarchar(120), SZUSINFO20 nvarchar(30), SDTSERIAL nvarchar(70), SPTSERIAL nvarchar(50), SFABEZ nvarchar(120), SPRUEFER nvarchar(120), SZEICHBEZ nvarchar(80), SARTIKELNR nvarchar(50), SMANDBEZ nvarchar(80), DM101 decimal(38,10), DM102 decimal(38,10), DM103 decimal(38,10), DM104 decimal(38,10), DM105 decimal(38,10), DM106 decimal(38,10), DM9RMIN decimal(38,10), DM9RMAX decimal(38,10), DM9RAUSSEN decimal(38,10), DTLAENDERUNG datetime NOT NULL, DSM101 decimal(38,10), DSM102 decimal(38,10), DSM103 decimal(38,10), DSM104 decimal(38,10), DSM105 decimal(38,10), DSM106 decimal(38,10), DSM9RMIN decimal(38,10), DSM9RMAX decimal(38,10), DSM9RAUSSEN decimal(38,10), DMMANZAHL decimal(38,0))
ALTER TABLE MM_MITTELSTAND_CK ADD CONSTRAINT DF_MM_MITTELSTAND_CK DEFAULT (getdate()) FOR DTLAENDERUNG


CREATE TABLE _MAiT_MM_MITTELSTAND ( SPANR nvarchar(120), SZUSINFO20 nvarchar(30), SDTSERIAL nvarchar(70), SPTSERIAL nvarchar(50), SFABEZ nvarchar(120), SPRUEFER nvarchar(120), SZEICHBEZ nvarchar(80), SARTIKELNR nvarchar(50), SMANDBEZ nvarchar(80), DM101 decimal(38,10), DM102 decimal(38,10), DM103 decimal(38,10), DM104 decimal(38,10), DM105 decimal(38,10), DM106 decimal(38,10), DM9RMIN decimal(38,10), DM9RMAX decimal(38,10), DM9RAUSSEN decimal(38,10), DTLAENDERUNG datetime NOT NULL, DSM101 decimal(38,10), DSM102 decimal(38,10), DSM103 decimal(38,10), DSM104 decimal(38,10), DSM105 decimal(38,10), DSM106 decimal(38,10), DSM9RMIN decimal(38,10), DSM9RMAX decimal(38,10), DSM9RAUSSEN decimal(38,10), DMMANZAHL decimal(38,0))
ALTER TABLE _MAiT_MM_MITTELSTAND ADD CONSTRAINT _DF_MM_MITTELSTAND_CK DEFAULT (getdate()) FOR DTLAENDERUNG
-- CKCOnnect wefa2019$

CREATE TABLE _MAiT_MM_2DB_MITTELSTAND ( SPANR nvarchar(120), SZUSINFO20 nvarchar(30), SDTSERIAL nvarchar(70), SPTSERIAL nvarchar(50), SFABEZ nvarchar(120), SPRUEFER nvarchar(120), SZEICHBEZ nvarchar(80), SARTIKELNR nvarchar(50), SMANDBEZ nvarchar(80), DM101 decimal(38,10), DM102 decimal(38,10), DM103 decimal(38,10), DM104 decimal(38,10), DM105 decimal(38,10), DM106 decimal(38,10), DM1011 decimal(38,10), DM1012 decimal(38,10), DM1013 decimal(38,10), DM1014 decimal(38,10), DM1015 decimal(38,10), DM1016 decimal(38,10), DM1221 decimal(38,10), DD1M9RMIN decimal(38,10), DD1M9RMAX decimal(38,10), DD1M9RAUSSEN decimal(38,10), DD2M9RMIN decimal(38,10), DD2M9RMAX decimal(38,10), DD2M9RAUSSEN decimal(38,10), DTLAENDERUNG datetime NOT NULL, DSM101 decimal(38,10), DSM102 decimal(38,10), DSM103 decimal(38,10), DSM104 decimal(38,10), DSM105 decimal(38,10), DSM106 decimal(38,10), DSM1011 decimal(38,10), DSM1012 decimal(38,10), DSM1013 decimal(38,10), DSM1014 decimal(38,10), DSM1015 decimal(38,10), DSM1016 decimal(38,10), DSM1221 decimal(38,10), DD1SM9RMIN decimal(38,10), DD1SM9RMAX decimal(38,10), DD1SM9RAUSSEN decimal(38,10),DD2SM9RMIN decimal(38,10), DD2SM9RMAX decimal(38,10), DD2SM9RAUSSEN decimal(38,10), DMMANZAHL decimal(38,0))
ALTER TABLE _MAiT_MM_2DB_MITTELSTAND ADD CONSTRAINT _DF_MM_MITTELSTAND_2DB_CK DEFAULT (getdate()) FOR DTLAENDERUNG



--- Application Select 
 SELECT
 SPANR, SZUSINFO20, SDTSERIAL,
 SPTSERIAL, SFABEZ, SPRUEFER, 
 SZEICHBEZ, SARTIKELNR, SMANDBEZ, DM101, 
 DM102, DM103, DM104, 
 DM105, DM106, DM9RMIN, 
 DM9RMAX, DM9RAUSSEN, DSM101, 
 DSM102, DSM103, DSM104, 
 DSM105, DSM106, DSM9RMIN, 
 DSM9RMAX, DSM9RAUSSEN, DMMANZAHL, DTLAENDERUNG 
 FROM MM_MITTELSTAND_CK 
 WHERE SPANR = 'TEST 123' ORDER BY DTLAENDERUNG DESC


 DELETE FROM MM_MITTELSTAND_CK WHERE SPRUEFER = 'NVE'

 SELECT 
 SPANR, SZUSINFO20, SDTSERIAL, 
 SPTSERIAL, SFABEZ, SPRUEFER, 
 SZEICHBEZ, SARTIKELNR, SMANDBEZ, DM101, 
 DM102, DM103, DM104, 
 DM105, DM106, DM9RMIN, 
 DM9RMAX, DM9RAUSSEN, DSM101, 
 DSM102, DSM103, DSM104, 
 DSM105, DSM106, DSM9RMIN, 
 DSM9RMAX, DSM9RAUSSEN, DMMANZAHL, DTLAENDERUNG 
 FROM MM_MITTELSTAND_CK 
 WHERE SPANR = @spaNummer ORDER BY DTLAENDERUNG DESC"

UPDATE MM_MITTELSTAND_CK 
SET SPANR = '984' , SPTSERIAL = '985'
where SPANR = 'TEST 123'


/****** Script for SelectTopNRows command from SSMS  ******/
SELECT *
  FROM [qsystest].[dbo].[SPA_KOPF] INNER JOIN SPCIDREF ON SPA_KOPF.NLFDPANR = SPCIDREF.NLFDPANR
  INNER JOIN PP_PAB_PP_REV ON SPCIDREF.NLFDPABNR = PP_PAB_PP_REV.NLFDPABNR
  INNER JOIN MM_REV ON MM_REV.NLFDMMNR = PP_PAB_PP_REV.NLFDMMNR

SELECT MM_REV.DSOLL FROM MM_REV


SELECT MM_KOPF.SMMBEZ as 'MM-BEZ',
		MM_KOPF.SMMNR AS 'MM-NR',
		MM_REV.DSOLL AS 'SOLLMAß', 
		MM_REV.DTO AS 'Obere Tolerenz',
		MM_REV.DTU AS 'Untere Tolerenz',
		MM_REV.NEINHEIT AS NEINHEIT
		FROM MM_REV 
		INNER JOIN MM_KOPF ON MM_REV.NLFDMMNR = MM_KOPF.NLFDMMNR
		INNER JOIN PP_PAB_PP_REV ON MM_REV.NLFDMMNR = PP_PAB_PP_REV.NLFDMMNR
		INNER JOIN SPA_KOPF 
		INNER JOIN ARTIKEL ON SPA_KOPF.NLFDARTIKELNR = ARTIKEL.NLFDARTIKELNR 
		INNER JOIN PP_REV ON SPA_KOPF.NLFDPPLNR = PP_REV.NLFDPPLNR 
		INNER JOIN PP_PAB_REF ON PP_REV.NLFDPPLNR = PP_PAB_REF.NLFDPPLNR ON PP_PAB_PP_REV.NLFDPABNR = PP_PAB_REF.NLFDPABNR

			 ,
select * from MM_KOPF					
						   	  
SELECT  DISTINCT		SPA_KOPF.SPANR as Rückmeldenummer,
						MANDANT.SMANDBEZ as MANDANT,
						 FA_STAMM.SFABEZ as KUNDE,
						 MM_KOPF.SMMBEZ as 'MM-BEZ',
						 MM_KOPF.SMMNR AS 'MM-NR',
						 MM_REV.DTO AS 'Obere Tolerenz',
						 MM_REV.DTU AS 'Untere Tolerenz',
						 ARTIKEL.SZEICHNR as Zeichnungsnummer,
						ARTIKEL.SARTIKELNR AS Werkzeugnummer,
						ARTIKEL.SZEICHBEZ,
						MM_REV.DSOLL AS SOLLMAß,
						MM_REV.NEINHEIT,
						ARTIKEL.SZEICHBEZ
								 
FROM SPA_KOPF 
INNER JOIN SPCIDREF ON SPA_KOPF.NLFDPANR = SPCIDREF.NLFDPANR
INNER JOIN PP_PAB_PP_REV ON PP_PAB_PP_REV.NLFDPABNR = SPCIDREF.NLFDPABNR
INNER JOIN MM_REV ON MM_REV.NLFDMMNR = PP_PAB_PP_REV.NLFDMMNR
and MM_REV.NLFDMMSPEZNR = PP_PAB_PP_REV.NLFDMMSPEZNR
INNER JOIN MM_KOPF ON MM_REV.NLFDMMNR = MM_KOPF.NLFDMMNR
INNER JOIN PP_KOPF ON SPA_KOPF.NLFDPPLNR = PP_KOPF.NLFDPPLNR 
INNER JOIN ARTIKEL ON PP_KOPF.NLFDARTIKELNR = ARTIKEL.NLFDARTIKELNR 
INNER JOIN MANDANT ON SPA_KOPF.NLFDMANDNR=MANDANT.NLFDMANDNR 
INNER JOIN FA_STAMM ON SPA_KOPF.NLFDFANR=FA_STAMM.NLFDFANR WHERE SPA_KOPF.SPANR = 'TEST 123' order by MM_KOPF.SMMBEZ

use qsystest
SELECT * FROM PP_KOPF INNER JOIN ARTIKEL ON ARTIKEL.NLFDARTIKELNR = PP_KOPF.NLFDARTIKELNR

use wefa
sp_changedbowner qmstest


SELECT DISTINCT
SPA_KOPF.SPANR AS Rückmeldenummer, 
ARTIKEL.SARTIKELNR AS Werkzeugnummer, 
SPA_KOPF.SZUSINFO20 as Auftragsnummer, 
ARTIKEL.SZEICHNR as Zeichnungsnummer, 
FA_STAMM.SFABEZ as KUNDE,
MANDANT.SMANDBEZ as MANDANT, 
MM_KOPF.SMMBEZ as MMBEZ,
MM_KOPF.SMMNR AS MMNR,
MM_REV.DSOLL AS SOLLMASS, 
MM_REV.NEINHEIT, 
ARTIKEL.SZEICHBEZ 
FROM SPA_KOPF 
INNER JOIN SPCIDREF ON SPA_KOPF.NLFDPANR = SPCIDREF.NLFDPANR 
INNER JOIN PP_PAB_PP_REV ON PP_PAB_PP_REV.NLFDPABNR = SPCIDREF.NLFDPABNR 
INNER JOIN MM_REV ON MM_REV.NLFDMMNR = PP_PAB_PP_REV.NLFDMMNR 
AND MM_REV.NLFDMMSPEZNR = PP_PAB_PP_REV.NLFDMMSPEZNR 
INNER JOIN MM_KOPF ON MM_REV.NLFDMMNR = MM_KOPF.NLFDMMNR 
INNER JOIN PP_KOPF ON SPA_KOPF.NLFDPPLNR = PP_KOPF.NLFDPPLNR 
INNER JOIN ARTIKEL ON PP_KOPF.NLFDARTIKELNR = ARTIKEL.NLFDARTIKELNR 
INNER JOIN MANDANT ON SPA_KOPF.NLFDMANDNR = MANDANT.NLFDMANDNR  
INNER JOIN FA_STAMM ON SPA_KOPF.NLFDFANR = FA_STAMM.NLFDFANR 
WHERE(SPA_KOPF.SPANR = 'TEST 123') // AND (PP_REV.NREVFLAG = '1')"

SELECT DISTINCT
SPA_KOPF.SPANR,
ARTIKEL.SARTIKELNR,
SPA_KOPF.SZUSINFO20,
ARTIKEL.SZEICHNR,
FA_STAMM.SFABEZ,
ART_FA.SSERIAL
FROM   MM_REV
INNER JOIN PP_PAB_PP_REV ON MM_REV.NLFDMMNR = PP_PAB_PP_REV.NLFDMMNR
INNER JOIN SPA_KOPF
INNER JOIN ARTIKEL ON SPA_KOPF.NLFDARTIKELNR = ARTIKEL.NLFDARTIKELNR
INNER JOIN PP_REV ON SPA_KOPF.NLFDPPLNR = PP_REV.NLFDPPLNR
INNER JOIN PP_PAB_REF ON PP_REV.NLFDPPLNR = PP_PAB_REF.NLFDPPLNR ON PP_PAB_PP_REV.NLFDPABNR = PP_PAB_REF.NLFDPABNR 
INNER JOIN MANDANT ON SPA_KOPF.NLFDMANDNR = MANDANT.NLFDMANDNR
INNER JOIN FA_STAMM ON SPA_KOPF.NLFDFANR = FA_STAMM.NLFDFANR
INNER JOIN MM_KOPF ON MM_REV.NLFDMMNR = MM_KOPF.NLFDMMNR
INNER JOIN ART_FA ON SPA_KOPF.NLFDFANR = ART_FA.NLFDFANR
WHERE (SPA_KOPF.SPANR = 'Test 123') AND (PP_REV.NREVFLAG ='1') AND (ART_FA.SZUSINFOFELD1 = SPA_KOPF.SZUSINFO20)


/*OLD KOPFDATA SQL*/

SELECT DISTINCT
SPA_KOPF.SPANR AS Rückmeldenummer,
SPA_KOPF.SZUSINFO20 as Auftragsnummer, 
FA_STAMM.SFANR as KUNDE, 
MANDANT.SMANDBEZ as MANDANT, 
MM_KOPF.SMMBEZ as MMBEZ, 
MM_KOPF.SMMNR AS MMNR, 
MM_REV.DSOLL AS SOLLMASS, 
MM_REV.NEINHEIT, 
MM_REV.DTO AS OT, 
MM_REV.DTU AS UT
FROM SPA_KOPF
INNER JOIN SPCIDREF ON SPA_KOPF.NLFDPANR = SPCIDREF.NLFDPANR
INNER JOIN PP_PAB_PP_REV ON PP_PAB_PP_REV.NLFDPABNR = SPCIDREF.NLFDPABNR 
INNER JOIN MM_REV ON MM_REV.NLFDMMNR = PP_PAB_PP_REV.NLFDMMNR 
AND MM_REV.NLFDMMSPEZNR = PP_PAB_PP_REV.NLFDMMSPEZNR
INNER JOIN MM_KOPF ON MM_REV.NLFDMMNR = MM_KOPF.NLFDMMNR 
INNER JOIN PP_KOPF ON SPA_KOPF.NLFDPPLNR = PP_KOPF.NLFDPPLNR 
INNER JOIN MANDANT ON SPA_KOPF.NLFDMANDNR = MANDANT.NLFDMANDNR  
INNER JOIN FA_STAMM ON SPA_KOPF.NLFDFANR = FA_STAMM.NLFDFANR 
WHERE(SPA_KOPF.SPANR = '1073163')



/*FINAL SQL*/
SELECT  DISTINCT
SPA_KOPF.SPANR as 'RMN',
ARTIKEL.SARTIKELBEZ,
ZUSINFOPA.SINFO,
ARTIKEL.SZEICHNR,
ART_FA.SSERIAL,
FA_STAMM.SFABEZ
FROM   MM_REV
INNER JOIN PP_PAB_PP_REV ON MM_REV.NLFDMMNR = PP_PAB_PP_REV.NLFDMMNR
INNER JOIN SPA_KOPF
INNER JOIN ARTIKEL ON SPA_KOPF.NLFDARTIKELNR = ARTIKEL.NLFDARTIKELNR
INNER JOIN PP_REV ON SPA_KOPF.NLFDPPLNR = PP_REV.NLFDPPLNR
INNER JOIN PP_PAB_REF ON PP_REV.NLFDPPLNR = PP_PAB_REF.NLFDPPLNR ON PP_PAB_PP_REV.NLFDPABNR = PP_PAB_REF.NLFDPABNR
INNER JOIN ART_FA ON ART_FA.NLFDARTIKELNR = ARTIKEL.NLFDARTIKELNR
INNER JOIN FA_STAMM ON ART_FA.NLFDFANR = FA_STAMM.NLFDFANR
INNER JOIN MANDANT ON SPA_KOPF.NLFDMANDNR = MANDANT.NLFDMANDNR
INNER JOIN ZUSINFOPA ON SPA_KOPF.NLFDPANR = ZUSINFOPA.NLFDPANR
WHERE SPA_KOPF.SPANR = '1073163' AND (PP_REV.NREVFLAG ='1') AND (ART_FA.SZUSINFOFELD1 = ZUSINFOPA.SINFO)

SELECT  DISTINCT
SPA_KOPF.SPANR,
ARTIKEL.SARTIKELBEZ,
ZUSINFOPA.SINFO,
ARTIKEL.SZEICHNR,
FA_STAMM.SFANR,
ART_FA.SSERIAL
FROM   MM_REV
INNER JOIN PP_PAB_PP_REV ON MM_REV.NLFDMMNR = PP_PAB_PP_REV.NLFDMMNR
INNER JOIN SPA_KOPF
INNER JOIN ARTIKEL ON SPA_KOPF.NLFDARTIKELNR = ARTIKEL.NLFDARTIKELNR
INNER JOIN PP_REV ON SPA_KOPF.NLFDPPLNR = PP_REV.NLFDPPLNR
INNER JOIN PP_PAB_REF ON PP_REV.NLFDPPLNR = PP_PAB_REF.NLFDPPLNR ON PP_PAB_PP_REV.NLFDPABNR = PP_PAB_REF.NLFDPABNR
INNER JOIN ART_FA ON ART_FA.NLFDARTIKELNR = ARTIKEL.NLFDARTIKELNR
INNER JOIN FA_STAMM ON ART_FA.NLFDFANR = FA_STAMM.NLFDFANR
INNER JOIN MANDANT ON SPA_KOPF.NLFDMANDNR = MANDANT.NLFDMANDNR
INNER JOIN ZUSINFOPA ON SPA_KOPF.NLFDPANR = ZUSINFOPA.NLFDPANR
INNER JOIN MM_KOPF ON MM_REV.NLFDMMNR = MM_KOPF.NLFDMMNR
WHERE (SPA_KOPF.SPANR = '1073163') AND (PP_REV.NREVFLAG ='1') AND (ART_FA.SZUSINFOFELD1 = ZUSINFOPA.SINFO) 

SELECT DISTINCT
SPA_KOPF.SPANR AS Rückmeldenummer,
ARTIKEL.SARTIKELBEZ AS Werkzeugnummer, 
SPA_KOPF.SZUSINFO20 as Auftragsnummer, 
ARTIKEL.SZEICHNR as Zeichnungsnummer, 
FA_STAMM.SFANR as KUNDE, 
MANDANT.SMANDBEZ as MANDANT, 
MM_KOPF.SMMBEZ as MMBEZ, 
MM_KOPF.SMMNR AS MMNR, 
MM_REV.DSOLL AS SOLLMASS, 
MM_REV.NEINHEIT, 
ARTIKEL.SZEICHBEZ,
MM_REV.DTO AS OT, 
MM_REV.DTU AS UT
FROM SPA_KOPF
INNER JOIN SPCIDREF ON SPA_KOPF.NLFDPANR = SPCIDREF.NLFDPANR
INNER JOIN PP_PAB_PP_REV ON PP_PAB_PP_REV.NLFDPABNR = SPCIDREF.NLFDPABNR 
INNER JOIN MM_REV ON MM_REV.NLFDMMNR = PP_PAB_PP_REV.NLFDMMNR 
AND MM_REV.NLFDMMSPEZNR = PP_PAB_PP_REV.NLFDMMSPEZNR
INNER JOIN MM_KOPF ON MM_REV.NLFDMMNR = MM_KOPF.NLFDMMNR 
INNER JOIN PP_KOPF ON SPA_KOPF.NLFDPPLNR = PP_KOPF.NLFDPPLNR 
INNER JOIN ARTIKEL ON PP_KOPF.NLFDARTIKELNR = ARTIKEL.NLFDARTIKELNR 
INNER JOIN ART_FA ON ART_FA.NLFDARTIKELNR = ARTIKEL.NLFDARTIKELNR
INNER JOIN MANDANT ON SPA_KOPF.NLFDMANDNR = MANDANT.NLFDMANDNR  
INNER JOIN FA_STAMM ON ART_FA.NLFDFANR = FA_STAMM.NLFDFANR 
WHERE(SPA_KOPF.SPANR = '1073163')


